### ISSUE TITLE
Extract setup.js to its own repository

### ISSUE THREAD

**Issue by DamienCassou** [asamuzaK/withExEditorHost#10]
Hi,

I would like to reuse your setup.js and browser-data.js in the context of another web extension. Would it make sense to extract that to its own project so people can just include it using package.json without getting withExEditorHost? I can take care of the extraction if you want to.

**Comment by asamuzaK** [comment]
Depends on #9 
Extract setup.js stand-alone is not so useful.
I'm thinking of implement both native-message.js and setup.js in single repository.
