### ISSUE TITLE
Setup: Editor-path only in 8.3 style?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [asamuzaK/withExEditorHost#100]
Win 10 64 German, FF85
I tried to enter the editor path and got this:

```
Input editor path: "C:\Program Files\Notepad++"
"C:\Program Files\Notepad++" is not executable.
Input editor path: "C:\Program Files\Notepad++\"
"C:\Program Files\Notepad++" is not executable.
Input editor path: "C:\Programme\Notepad++\notepad++.exe"
"C:\Programme\Notepad++\notepad++.exe" is not executable.
Input editor path: "C:\Program Files\Notepad++\notepad++.exe"
"C:\Program Files\Notepad++\notepad++.exe" is not executable.
Input editor path: C:\PROGRA~1\NOTEPA~1\NOTEPA~1.EXE
```

I tried it with pure path (with and without trailing backslash), with quoted path+file in German ("Programme") and English ("Program Files") - and failed all the times. Only the pure 8.3-style was accepted.
Is this by intention?

**Comment by asamuzaK** [comment]
```
Input editor path: C:\Program Files\Notepad++\notepad++.exe
```

Please try again without quotes.

**Comment by asamuzaK** [comment]
Still in trouble?

**Comment by Pierre-de-la-Verre** [comment]
It did not change on this special PC. Another colleagues told me that on other PCs is works fine - although the first two infos (Host compatibility and..?? - I don't know, I'm not on this PC at the moment ...) are both on "incompatible"...
It will be further watched by my colleague ..

**Comment by asamuzaK** [comment]
I installed notepad++ and tested myself.
`C:\Program Files\Notepad++\notepad++.exe` works fine for me.

**Comment by asamuzaK** [comment]
I made the warning message a little more detailed.
Try using the pre-release version.

If you are using binary, download from [Release v6.1.0-a.1](https://github.com/asamuzaK/withExEditorHost/releases/tag/v6.1.0-a.1)

Or, if you are using npm version, run below.
```
npm i -g withexeditorhost@next
```

**Comment by Pierre-de-la-Verre** [comment]
Thanks, works fine for me.
