### ISSUE TITLE
Using withExEditor with Chrome Remote Desktop

### ISSUE THREAD

**Issue by rtoy** [asamuzaK/withExEditorHost#102]
I use [Chrome Remote Desktop](https://remotedesktop.google.com/) sometimes to access my machine from a remote location.  I'd like to use withExEditor, but the withExEditorHost installer doesn't know where to install the files.

It would be nice if the installer knew, but I'd be ok if there were instructions on where exactly to install these.

chrome://version says the profile path is "~/.config/chrome-remote-desktop/chrome-config/google-chrome-beta/Profile 1", at least for my linux machine.

**Comment by asamuzaK** [comment]
Try below and tell me the result.
I think there is a file "~/.config/google-chrome-beta/NativeMessagingHosts/withexeditorhost.json".
Copy that file to "~/.config/chrome-remote-desktop/chrome-config/google-chrome-beta/NativeMessagingHosts/withexeditorhost.json"
Restart Chrome beta.

**Comment by rtoy** [comment]
This works beautifully!  I'm using withExEditor to enter this comment.  This solution is good enough for me; I don't need the installer, as long as the README mentions this manual method.

Thanks!

**Comment by asamuzaK** [comment]
I'll close this, but PR welcome.
