### ISSUE TITLE
Google Chrome Beta path changed on MacOS

### ISSUE THREAD

**Issue by rtoy** [asamuzaK/withExEditorHost#103]
When running the installer, there's no option for installing for Chrome Beta for MacOS.  This used to work, but in some recent update, withExEditor no longer works.  The profile directory is now `~/Library/Application Support/Google/Chrome Beta/Default'.  I copied the json file from the old Chrome dir to `~/Library/Application Support/GoogleChrome Beta/NativeMessagingHosts`, and it seems to work; I'm using it to edit this message.

**Comment by asamuzaK** [comment]
Is it announced or documented somewhere?

**Comment by rtoy** [comment]
Not that I'm aware of.  https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md#Mac-OS-X doesn't even mention beta.

**Comment by rtoy** [comment]
It's being updated now to say the path is `Google/Chrome Beta`.  Likewise for Windows. It should be available now or very soon.

**Comment by asamuzaK** [comment]
You mean that `~/Library/Application Support/Google/Chrome Beta/` is the correct path?
If so there is no need to fix, right?

**Comment by rtoy** [comment]
IIRC, the installer had no option for mac os beta because it used to work for both Chrome and Chrome Beta.  Now it doesn't and the installer needs an option for beta to install it to "Google/Chrome Beta/".

**Comment by asamuzaK** [comment]
It does.
You pointed that out and I fixed it before.
See #98
Source code [webExtNativeMsg/browser-data.js](https://github.com/asamuzaK/webExtNativeMsg/blob/master/modules/browser-data.js#L44)

**Comment by rtoy** [comment]
This is what I see on MacOS:
```
 npm run setup

> withexeditorhost@6.1.0 setup /Users/rtoy/src/github/withExEditorHost
> node ./index.js setup


[1] firefox
[2] waterfoxcurrent
[3] chrome
[4] chromecanary
[5] chromium
[6] brave
[7] edge
[8] opera
[9] vivaldi
[0] CANCEL
```
Sorry about forgetting about #98.

I'm perfectly happy to copy the json file over as needed.

**Comment by asamuzaK** [comment]
What is `/Users/rtoy/src/github/withExEditorHost`?
Is it a copy or a fork of this repo?
Running host from source is not recommended, so remove that.

* run `npm i -g withexeditorhost@latest`
* run `npm root -g`, I think it will echo something like `/usr/local/lib/node_modules/`
* cd to the host, for example, `cd /usr/local/lib/node_modules/withexeditorhost`
* run `npm run setup`

For details see https://github.com/asamuzaK/withExEditorHost#host-setup-from-npm

**Comment by asamuzaK** [comment]
@rtoy Still in trouble?

**Comment by rtoy** [comment]
Sorry for the delay!  I tried out the new scheme in https://github.com/asamuzaK/withExEditorHost/issues/103#issuecomment-823601959, and it works great!

I think I was using a clone because that was how to get it originally.  I don't need the clone anymore, which is very nice.

Everything is working fine now.

Thanks for patience and help and especially for this awesome extension that I can't live without!
