### ISSUE TITLE
Workflow with iterative edits

### ISSUE THREAD

**Issue by richardb64** [asamuzaK/withExEditorHost#107]
A common workflow that worked with ItsAllText goes something like this (using MediaWiki as an example):

1. Open the page edit tab.
2. Click the "Show preview" button once (a workaround for a field naming issue that affected IAT too).
3. Invoke the external editor on the main edit box.
4. Edit the text.
5. Save the text in the external editor, without closing it.
6. Observe that the browser has updated to track the latest edits.
7. Click the "Show preview" button to view the formatted results.
8. Repeat from 4 as required.

With WEE, as has been reported in some other issues (notably #28) and AMO comments, this doesn't work.

I can save the text multiple times (ie. repeating just steps 4-6), and the browser tracks the changes.  But as soon as the page refreshes (step 7), the editor becomes permanently detached.  Future saves are not picked up by the browser, and are lost if you then close the external editor.

Can this be fixed, or does the WebExtensions model mean it's impossible to have a "persistent" linkage that survives page reloads?

**Comment by asamuzaK** [comment]
Try below.

8. Right click on the main text field again, and click `Edit text with YourEditor` menu item.
9. The local file should be synced again.
10. Repeat from 4 as needed.

**Comment by richardb64** [comment]
That does kinda work, thanks.  It's a bit messy, though - at least with my preferred editor (gvim), it opens a _new_ window on the same file as before.  Because vim knows the file is already open, the new window shows a modal question that I have to answer before I can continue editing.  I can't just go back to the original window either - that recognises that the file has been written by WEE (even though hopefully the text is still the same), and presents a modal question of its own.  And in most cases I'll have lost my place in the file, undo history will be cleared, etc.

Also, if I forget to re-invoke WEE once before continuing to edit, I'm back in the situation where those edits are lost.

Is it possible for WEE to _query_ WEEH to see if there is already a file present, with an active editor session, and automatically resync if it finds one (or rather, re-establish the "watcher" and resync next time the editor updates the file)?

**Comment by asamuzaK** [comment]
Change your editor setting
https://superuser.com/questions/181377/auto-reloading-a-file-in-vim-as-soon-as-it-changes-on-disk

**Comment by asamuzaK** [comment]
If the web page is moves to another page or reloaded, the port is disconnected.
And when the add-on detects that the port has been disconnected, both add-on's background script and the host removes the data they previously held.
Keeping data in place can lead to memory leaks.
