### ISSUE TITLE
Support LibreWolf

### ISSUE THREAD

**Issue by OrionRandD** [asamuzaK/withExEditorHost#108]
My host stopped working:

Host Connection Disconnected
Host Compatibility Incompatible. Upgrade the host to v7.0.0 or higher.
Editor State Unknown

**Comment by OrionRandD** [comment]
> My host stopped working:
> 
> Host Connection Disconnected Host Compatibility Incompatible. Upgrade the host to v7.0.0 or higher. Editor State Unknown

I have discovered that the problem is my browser ->  librewolf -> https://librewolf-community.gitlab.io/ 
the Host was working with it 5 days ago. But, no more...
Waterfox is working ok with the HOST 
Could you add support for librewolf? My prefered browser...

**Comment by asamuzaK** [comment]
If the host worked before, maybe upgrade wasn't done correctly?

Please tell me below.
What is the OS?
Which host you're using, binary or npm?

**Comment by OrionRandD** [comment]
> If the host worked before, maybe upgrade wasn't done correctly?
> The upgrade was done correctly....
> Please tell me below. What is the OS? Which host you're using, binary or npm?
Debian an npm...
The problem is in Librewolf....
It is working in Waterfox...
That's why I asked you to add support for Librewolf...
I do not know what happened. 
Because, Librewolf was working ok with withexeditor addon...

**Comment by asamuzaK** [comment]
Please try below and tell me the result.
I'll add librewolf support if this works.

* Close librewolf
* Copy either
  `$HOME/.mozilla/native-messaging-hosts/withexeditorhost.json`
  or
  `$HOME/.waterfox/native-messaging-hosts/withexeditorhost.json`
  to
  `$HOME/.librewolf/native-messaging-hosts/withexeditorhost.json`
* Restart librewolf

**Comment by OrionRandD** [comment]
I did not have this folder and file:
$HOME/.librewolf/native-messaging-hosts/withexeditorhost.json
Working now!  :)
Thx

**Comment by asamuzaK** [comment]
Uploaded the test package `v7.0.1-b4`.
Follow below.

* Close librewolf
* Install test package by `npm i -g withexeditorhost@next`
* Move to npm global path and cd to withexeditorhost
  On linux, it should be `$HOME/.npm-global/lib/node_modules/withexeditorhost/`
  If you can't find it there, check with `npm root -g`
* Run `npm run setup`
  If you are prompt to overwrite `withexeditorhost.json`, answer `y`
  Enter editor path and command args
* After setup is done, check the following
  * Open `$HOME/.config/withexeditorhost/config/librewolf/`
    Make sure `withexeditorhost.sh` and `editorconfig.json` is in that directory
  * Open `$HOME/.librewolf/native-messaging-host/withexeditorhost.json`
    Make sure that the value of the path is pointing to `withexeditorhost.sh`

**Comment by OrionRandD** [comment]
For some reason it is now working using the global path:
/usr/lib/node_modules/withexeditorhost/
Thx a lot again...

**Comment by asamuzaK** [comment]
You're right, prefix is /usr/local/ on Linux. [prefix Configuration](https://docs.npmjs.com/cli/v8/configuring-npm/folYou're right, prefix is /usr/local/ on Linux. [prefix Configuration](https://docs.npmjs.com/cli/v8/configuring-npm/folders#prefix-configuration)

I'll close this.
ders#prefix-configuration)

I'll close this.
