### ISSUE TITLE
v7 doesn't run on Debian 10 (buster) anymore.

### ISSUE THREAD

**Issue by erAck** [asamuzaK/withExEditorHost#109]
On Debian 10 (buster) for withExEditorHost starting with 6.1.0 running `ldd ./index` gives
```
./index: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./index)
./index: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./index)
```
=> not usable.

Could you provide a compatibility package built on/for such oldstable systems?

**Comment by asamuzaK** [comment]
The binaries are compiled in a virtual environment provided by GitHub Actions, and it seems that Ubuntu 20.04 is currently used for Linux.
See [About GitHub-hosted runners - GitHub Docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

WithExEditorHost is also available as an [npm package](https://www.npmjs.com/package/withexeditorhost).
Install Node.js and try using the npm package.
See [Host setup from npm](https://github.com/asamuzaK/withExEditorHost#host-setup-from-npm)

**Comment by asamuzaK** [comment]
I've already presented a solution, so I'll treat it as WONTFIX and close the issue.
