### ISSUE TITLE
Problem upgrading: Cannot find package 'https-proxy-agent'

### ISSUE THREAD

**Issue by chriscroome** [asamuzaK/withExEditorHost#110]
When trying to upgrade I get:

```bash
npm run setup -- --browser=firefox

> withexeditorhost@7.0.3 setup /example/path/withExEditorHost
> node ./index.js setup "--browser=firefox"

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'https-proxy-agent' imported from /example/path/withExEditorHost/modules/main.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! withexeditorhost@7.0.3 setup: `node ./index.js setup "--browser=firefox"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the withexeditorhost@7.0.3 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /example/path/.npm/_logs/2022-02-16T13_42_05_575Z-debug.log
```

This is with these versions:

```bash
npm --version
6.14.16
node --version
v14.19.0
```
On Debian Bullseye.

**Comment by asamuzaK** [comment]
Cannot be reproduced
Please uninstall withexeditorhost and then reinstall it

**Comment by asamuzaK** [comment]
Maybe it's safer to do an overwrite install with `npm i -g` instead of `npm up -g`.
I have changed the documentation.

**Comment by asamuzaK** [comment]
Maybe related?
[\[BUG\] `npm update -g package@latest` removes all global packages · Issue #3175 · npm/cli](https://github.com/npm/cli/issues/3175)

**Comment by chriscroome** [comment]
I haven't been using `npm i -g` or `npm up -g`, I have [Node.JS installed using a `.deb`](https://git.coop/webarch/nodejs).

**Comment by asamuzaK** [comment]
If you can't use npm, consider using binaries.

**Comment by asamuzaK** [comment]
btw, how did you install withExEditorHost the first time?

**Comment by chriscroome** [comment]
It was years ago but I believe I simply cloned the repo I have been updating it using a Bash script containing:

```
#!/bin/bash

cd ~/withExEditorHost
git stash
git pull
npm run setup -- --browser=firefox
```

**Comment by asamuzaK** [comment]
Running host from source is not recommended anymore.
* Remove source
* Run `npm i -g withexeditorhost`
* Move to the installed directory.
  `cd /usr/local/lib/node_modules/withexeditorhost`.
  NOTE: On Linux global node_modules directory is basically `/usr/local/lib/node_modules`, in case you can't find that, run `npm root -g`.
* Run `npm run setup -- --browser=firefox`

**Comment by chriscroome** [comment]
Thanks, I'll give that a go :+1:
