### ISSUE TITLE
Incompatible after updating to v7.0.7

### ISSUE THREAD

**Issue by rtoy** [asamuzaK/withExEditorHost#111]
I got a notification that I needed to update the host to v7.0.0 or later.  As usual, I followed the directions to update the host using npm install.

After successfully installing the latest version (7.0.7) and configuring for Firefox, withExEditor now says it's disconnected because it's incompatible and I should upgrade to v7.0.0 or later.

Not sure what to do now.  I've updated the host via npm many times before without problems.  It appears that I'm using version 10.0.0 of withExEditor.

**Comment by asamuzaK** [comment]
What happenes if you  restart Firefox?

**Comment by rtoy** [comment]
Oh, sorry.  That takes care of it.  I had previously just use the Reload withExEditor button whenever I updated the host and that always worked.

Everything is working fine.  Sorry for the noise.

**Comment by richardb64** [comment]
Even reverting to 7.0.6 doesn't restore the extension to working order.  I can try restarting the whole browser if that's really the only answer, but that should only ever be a last resort.   It's a bad regression if a restart is now required whenever withExEditorHost is updated.  Has something changed in this area?
