### ISSUE TITLE
Possible to launch VSCode-web as external editor?

### ISSUE THREAD

**Issue by ddirks** [asamuzaK/withExEditorHost#112]
I have configured withExEditorHost to launch the desktop version of Visual Studio Code as the external editor; this works perfectly.

I am wondering if it would be possible to withExEditor to open files in VSCode for the Web (https://vscode.dev/), but so far I have not been able to figure out the correct configuration.

Thank you for any insights!

**Comment by asamuzaK** [comment]
Out of scope.
This extension is intended for local editors on a PC, not for online editors.

**Comment by asamuzaK** [comment]
FYI, there was a question about using withExEditor with Chrome Remote Desktop.
That's possible.
[Using withExEditor with Chrome Remote Desktop · Issue #102 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/issues/102)

**Comment by ddirks** [comment]
Thanks, I understand. I appreciate your work on withExEditor!
