### ISSUE TITLE
updates require restart on firefox 117

### ISSUE THREAD

**Issue by jcbradfield** [asamuzaK/withExEditorHost#116]
With the current add-on version, and firefox 117, it took a long time to get it working again. Eventually I found that restarting firefox seems to fix it. But even if I remove withexeditor, restart, and install it again, I still have to restart firefox to see it working.
There used to be a "reload withexeditor" button, I think. Is there some way round this issue?

**Comment by asamuzaK** [comment]
Cannot reproduce.
Please provide detailed steps to reproduce.

**Comment by asamuzaK** [comment]
No additional info.
Closing.
