### ISSUE TITLE
script issue

### ISSUE THREAD

**Issue by OrionRandD** [asamuzaK/withExEditorHost#120]
I am getting this error, using the script to install the host:

./index setup
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module './xhr-sync-worker.js'
Require stack:
- /home/vagner/.local/bin/withExEditorHost/index
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at /home/vagner/.local/bin/withExEditorHost/index:892:12145
    at /home/vagner/.local/bin/withExEditorHost/index:1:214
    at /home/vagner/.local/bin/withExEditorHost/index:893:20617
    at /home/vagner/.local/bin/withExEditorHost/index:1:214
    at /home/vagner/.local/bin/withExEditorHost/index:899:73065
    at /home/vagner/.local/bin/withExEditorHost/index:1:214
    at /home/vagner/.local/bin/withExEditorHost/index:899:79984
    at /home/vagner/.local/bin/withExEditorHost/index:1:214 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/vagner/.local/bin/withExEditorHost/index' ]
}

Node.js v20.11.1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

I have this module here:
/home/vagner/.vscode/extensions/yzane.markdown-pdf-1.5.0/node_modules/jsdom/lib/jsdom/living/xhr-sync-worker.js

But, the script does not find it...

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by asamuzaK** [comment]
Yeah, seems like a regression in Node.js v20.11.1

**Comment by asamuzaK** [comment]
Node.js v20.11.1 is a security fix, ref [Node.js — Wednesday February 14 2024 Security Releases](https://nodejs.org/en/blog/vulnerability/february-2024-security-releases), so I have released a package that bundles it.

A temporary workaround is to revert to v8.0.0.
The security issues are not patched, but since it is limited to the interaction between the host and the extension, I think it can be said that there is almost no risk.

**Comment by OrionRandD** [comment]
> Node.js v20.11.1 is a security fix, ref [Node.js — Wednesday February 14 2024 Security Releases](https://nodejs.org/en/blog/vulnerability/february-2024-security-releases), so I have released a package that bundles it.
> 
> A temporary workaround is to revert to v8.0.0. The security issues are not patched, but since it is limited to the interaction between the host and the extension, I think it can be said that there is almost no risk.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

Could you fix the script?
I use it to install the host...

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by asamuzaK** [comment]
Just overwrite your binary with v8.0.0

**Comment by OrionRandD** [comment]
> Just overwrite your binary with v8.0.0

It is compressed in /tmp/withExEditorHost.tar.gz
???

**Comment by asamuzaK** [comment]
* Download package from [Release v8.0.0 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/releases/tag/v8.0.0)
* Extract package
* Overwrite current `index` with the extracted one

**Comment by OrionRandD** [comment]
> * Download package from [Release v8.0.0 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/releases/tag/v8.0.0)
> 
>     * Extract package
> 
>     * Overwrite current `index` with the extracted one

Works, but still points to the new version

[withExEditorHost](https://github.com/asamuzaK/withExEditorHost) New version v8.0.1 is available.
And if someone tries to upgrade it will face the previous error...
Thx

**Comment by asamuzaK** [comment]
It was a dependency issue.

**Comment by asamuzaK** [comment]
Released [v8.0.5](https://github.com/asamuzaK/withExEditorHost/releases/tag/v8.0.5)
