### ISSUE TITLE
is the script working or is it just me?

### ISSUE THREAD

**Issue by OrionRandD** [asamuzaK/withExEditorHost#125]
I have tried to upgrade the host with the script a bunch of times, but it seems not to be working...
And I have get this warning again and again:

withExEditorHost
Host Connection Disconnected
Host Compatibility Incompatible. Upgrade the host to v7.0.0 or higher. 

Something is wrong either on my side or with the script. It used to work here for a few years...

**Comment by asamuzaK** [comment]
[Follow this](https://github.com/asamuzaK/withExEditorHost/issues/120#issuecomment-1960592935)

**Comment by asamuzaK** [comment]
FYI, withExEditor for Blink (Chrome and its variants) will be discontinued soon as it cannot be migrated to MV3.
See [Announcement](https://github.com/asamuzaK/withExEditor/issues/166#issuecomment-1962765650)

**Comment by OrionRandD** [comment]
> FYI, withExEditor for Blink (Chrome and its variants) will be discontinued soon as it cannot be migrated to MV3. See [Announcement](https://github.com/asamuzaK/withExEditor/issues/166#issuecomment-1962765650)

I do not use Chrome, but Chromium and Firefox...
Thx for replying, seems to be working now...
But, in future upgrades, will the script still work?

**Comment by asamuzaK** [comment]
Same with Chromium.
I will continue to provide withExEitor for Firefox.

**Comment by rtoy** [comment]
I'm sad that withExEditor no longer works for Chrome.  But many thanks for your support over the years; it's been a great tool on Chrome when I needed to use Chrome (at work), but I mostly use Firefox so I'm grateful to you that Firefox will still be supported.

Thank you.
