### ISSUE TITLE
Setup aborted: Failed to create registry key.

### ISSUE THREAD

**Issue by uwabami** [asamuzaK/withExEditorHost#126]
Hi,  
When I try to update withExEditorHost, I get the following error and cannot update.

> PS C:\Users\uwabami\AppData\Roaming\npm\node_modules\withexeditorhost> npm run setup
>
> withexeditorhost@8.0.8 setup
> node ./index.js setup
>
> [1] firefox
> [2] waterfoxcurrent
> [3] librewolf
> [4] chrome
> [5] chromebeta
> [6] chromecanary
> [7] brave
> [8] edge
> [9] opera
> [a] vivaldi
> [0] CANCEL
> 
> Select a browser. [1...9, a, 0]: 1
> C:\Users\uwabami\AppData\Roaming\withexeditorhost\config\firefox already exists.
> Overwrite? [y/n]: y
> Created: C:\Users\uwabami\AppData\Roaming\withexeditorhost\config\firefox
> Created: C:\Users\uwabami\AppData\Roaming\withexeditorhost\config\firefox\withexeditorhost.cmd
> Created: C:\Users\uwabami\AppData\Roaming\withexeditorhost\config\firefox\withexeditorhost.json
> stderr: �G���[: �L�[���������ł��B
> "REG ADD /?" �Ɠ��͂���Ǝg�p�@���\������܂��B
>
> Setup aborted: Failed to create registry key.

**Comment by asamuzaK** [comment]
confimed

**Comment by asamuzaK** [comment]
Released v8.0.10
