### ISSUE TITLE
Use environment variable in editorconfig.json

### ISSUE THREAD

**Issue by mb720** [asamuzaK/withExEditorHost#128]
Hi and thanks again for withExEditorHost!

Is there currently a way to have environment variables resolved in editorconfig.json?

I tried

    "editorPath": "/usr/bin/${TERMINAL}",

to no avail. In my Bash, `echo $TERMINAL` prints "kitty".

Thanks in advance!

**Comment by asamuzaK** [comment]
Like this?
* Accept environment variable during setup
  e.g. `/usr/bin/${TERMINAL}` as user input
* Save resolved value in editorConfig.json
  e.g. `"editorPath": "/usr/bin/kitty"`

Or is there a reason you want to save user input as is?

**Comment by asamuzaK** [comment]
Forget about the previous comment.

There is a possibility that sensitive data is held in the environment variable, we should save it as is.

**Comment by asamuzaK** [comment]
Forgot to cut the branch and committed it directly...

Anyway, the issue is fixed and you can use environment variable in `editorconfig.json`.

**Comment by mb720** [comment]
Thanks for implementing this so quickly. I'll try the feature once there's a new release.

**Comment by asamuzaK** [comment]
Released v8.1.1

**Comment by mb720** [comment]
I just used the new feature and it worked like a charm:

    "editorPath": "/usr/bin/${TERMINAL}",

Thanks again. Your response time is amazing 👍
