### ISSUE TITLE
Add how to run in readme and nodejs version

### ISSUE THREAD

**Issue by FabriceSalvaire** [asamuzaK/withExEditorHost#18]
It misses nodjs version (Fedora 26 has v6) and `node index.js`

**Comment by asamuzaK** [comment]
You don't need to run `node index.js` by yourself.
When the browser connects to the host, it runs.

The host requires node.js v8.x because async/await and URL class which are introduced in v8 are used.
So use 'n' or something and install node.js v8.x.
