### ISSUE TITLE
Add design note

### ISSUE THREAD

**Issue by FabriceSalvaire** [asamuzaK/withExEditorHost#19]
Would be nice to know why it now requires a nodejs server ? I guess webextensions doesn't permit to fork an executable ???

**Comment by FabriceSalvaire** [comment]
Answer should be there

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging

**Comment by asamuzaK** [comment]
Yes, that's the answer, it's the design of WebExtensions.
And the only reason why it requires node.js is that... I wrote native messaging host in node.js.
