### ISSUE TITLE
Firefox Containers

### ISSUE THREAD

**Issue by chriscroome** [asamuzaK/withExEditorHost#20]
I suspect this isn't an issue specific to withExEditorHost but is a more general issue with Firefox, however it might be worth flagging it up to users &mdash; if you have a site open in a Firefox container and it uses HTTP Authentication, when you right click "edit with" in a textarea you get the HTML source of the 401 Unauthorized page rather than  the content of the textarea.

**Comment by asamuzaK** [comment]
Thanks.
It looks rather an issue of the add-on than the host.
Would you please re-file this issue in [Issues · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/issues "Issues · asamuzaK/withExEditor")?

**Comment by chriscroome** [comment]
Good point! I have [done that](https://github.com/asamuzaK/withExEditor/issues/53).

**Comment by asamuzaK** [comment]
Thanks.
