### ISSUE TITLE
Process does not exit after ctrl-C

### ISSUE THREAD

**Issue by chr15m** [asamuzaK/withExEditorHost#25]
To replicate:

 * `node index.js` (stay in foreground)
 * "Edit with ..." from browser to launch editor.
 * Send some edits back to browser.
 * Close editor.
 * ctrl-C `index.js` process
 * `$ pgrep -f withExEditorHost`
 * Observe process is still running.

**Comment by chr15m** [comment]
Possible solutions:

 * https://www.npmjs.com/package/tree-kill
 * http://azimi.me/2014/12/31/kill-child_process-node-js.html

**Comment by asamuzaK** [comment]
Why are you executing `node index.js` manually?
You don't need to do that.
node will be executed when browser starts, and will quit when browser shuts down or when restarts withExEditor from options page.

**Comment by chr15m** [comment]
How does it know which `node` binary to use? How does it know where to find `index.js`?

> I suppose there are 2 node process running, if you execute node index.js manually?

No, there is only 1.

**Comment by asamuzaK** [comment]
See "App manifest" part [Native messaging - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging "Native messaging - Mozilla | MDN")

**Comment by chr15m** [comment]
@asamuzaK ah ok so it was connected when running `setup.js`. Got it. Thanks!

**Comment by asamuzaK** [comment]
1. When withExEditor starts, it sends a request for connection to the host.
   `runtime.connectNative("withexeditorhost")`;
2. Browser looks into a specific location and see if `withexeditorhost.json` exists.
3. Browser runs command written in the `path` field of `withexeditorhost.json`.
   Which is a shell script that executes Node.
   `path/to/node /path/to/index.js`.
4. Then the host and the browser gets connected.
