### ISSUE TITLE
When withExEditorHost goes wrong, there's no clear way to get diagnostic information

### ISSUE THREAD

**Issue by ssokolow** [asamuzaK/withExEditorHost#27]
During one of my test runs with `/usr/bin/gvim` as my editor, one of my tests as follows:

1. I chose "Edit Text with gvim" from the context menu
2. I saw a brief flicker of a window on another monitor which looked like my default gvim window geometry and colour.
3. My process monitor showed no gVim windows beyond the ones I'd already had open.
4. Selecting "Edit Text with gvim" again had no effect.
5. I had to restart withExEditor to get it working again.

By the time I thought to check whether you were feeding output to the browser console, it was too full of unrelated stuff for me to find anything helpful.

(eg. Did my invocation of the context menu result in an attempt to spawn a subprocess or not? If so, what was its exit code? etc.)

It'd be a good idea to put some clear diagnostic instructions in the options page.

**Comment by asamuzaK** [comment]
Open browser console (Ctrl+Shift+J)
Filter logs by adding `withexeditor` or `withexeditorhost` to the input field in the upright corner
What do you get?

**Comment by ssokolow** [comment]
By the time you responded, I had already restarted the browser to apply an update. I'll try to re-create the bug some time in the next little while.

Either way, this bug is about adding something equivalent to those instructions to the extension itself, so users as as likely as possible to know what to do quickly after the problem happens.

**Comment by asamuzaK** [comment]
Fixed in [Add notification by asamuzaK · Pull Request #76 · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/pull/76 "Add notification by asamuzaK · Pull Request #76 · asamuzaK/withExEditor")
