### ISSUE TITLE
"Text field is synced on focus" is not intuitive

### ISSUE THREAD

**Issue by ssokolow** [asamuzaK/withExEditorHost#28]
Because it's been a little while since I used withExEditor, when I saw the discussion leading up to the "Automatically Synchronize Edited Content On Specific Sites" option, I almost mistakenly concluded that it was impossible to trigger an update of the text field in the WebExtension-based version of withExEditor without closing the editor.

It's just not a very intuitive thing for input focus to result in such a drastic change.

I'd suggest providing some kind of indicator that appears when the field is unfocused while connected to an external editor. Maybe a `<div style="pointer-events: none;">` absolutely positioned over the center of the text field containing the text "Focus this field to update its contents from your editor"

Something like the attached mockup. (I also set `opacity: 0.25` on the text field for the mockup.)

![screenshot2](https://user-images.githubusercontent.com/46915/36467491-fe031a00-16ac-11e8-9f49-2e96244152ba.png)

**Comment by asamuzaK** [comment]
Will you re-file this issue in [Issues · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/issues "Issues · asamuzaK/withExEditor")?
Thanks.

**Comment by ssokolow** [comment]
Oops. Sorry. 

(I tend to overestimate how observant I am when I'm tired.)

**Comment by JontAlle** [comment]
I use withExEditor (WEE) all the time, with gvim. It is critical to my existence in fact.
When I save but not quit, I experience some randomness in what happens. It is not clear what is going on, but it does give me grief when it fails to eventually save some very complex edit, that I assumed I had saved.
With the previous "Its all text" (IAT) that WEE has replaced, when you saved your work (but do not exit), the
browser screen would glow yellow for a few seconds, to give you feedback that your edit was saved.
IAT was robust to what you did after that re the saved edits. I could go back to the browser page, and view it, an and now loose my edits. 
However with WEE, there are times after saving (without leaving gvim) that I come back to gvim and make more edits (corrections to previous edits), and then ZZ (save and terminate gvim), the edits are lost. It seems that there is something wrong with the handshake, and my edits may be being saved in a different file, or not saved at all. 
Needless to say, this is very frustrating, and also complex, as its not clear what I did to cause the loss of edits.
Thanks
Jont

**Comment by asamuzaK** [comment]
I feel sorry for you having some problem.
But if you do not give me anything about
* Steps to reproduce the issue
* What kind of error is logged in the browser console (Ctrl+Shift+j), if any
the issue will not be fixed.

**Comment by asamuzaK** [comment]
And, please comment to the active issue, this issue is closed.

**Comment by JontAlle** [comment]
On 02/21/2018 10:23 AM, asamuzaK (Kazz) wrote:
>
> I feel sorry for you having some problem.
> But if you do not give me anything about
>
>   * Steps to reproduce the issue
>
some feedback re when the results are saved back to the source would be 
useful in diagnosing the problem
>
>   * What kind of error is logged in the browser console
>     (Ctrl+Shift+j), if any
>     the issue will not be fixed.
>
I dont know when it happens, its a bit random, so its difficult to get 
feedback.
