### ISSUE TITLE
Long URLs result in ENAMETOOLONG

### ISSUE THREAD

**Issue by smlx** [asamuzaK/withExEditorHost#3]
As the temporary file name is based on the URL of the current page, a very long URL can result in ENAMETOOLONG when the host tries to create the temporary file.

**Comment by asamuzaK** [comment]
Can you give me more info?
Like logs, steps to repoduce, your environment, etc.
There may be a log in Firefox Browser Console (Ctrl + Shift + J) too.
Thanks

**Comment by asamuzaK** [comment]
Released a test version which added max length when creating file name.
Please try.
[withExEditor :: Versions :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/versions/beta)

Current max length is 128.
If it's still too long, I'm planning to change that to 96 or 64.

**Comment by asamuzaK** [comment]
I'll close this issue as resolved.
If you still have it, please reopen.
