### ISSUE TITLE
Update host setup instructions

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/withExEditorHost#4]
Lots of people seems to be caught in trouble in similar places.
Setup instructions need to be easier to understand, but I am not a native English speaker.
Please give me some advises to update README.md
Thanks

**Comment by ssokolow** [comment]
The first thing I'd recommend is to build a list of examples of people having trouble so that contributors can get a good impression of where others are getting stuck.

**Comment by asamuzaK** [comment]
* Editor Config Path is not saved. [#issuecomment-286912973](https://github.com/asamuzaK/withExEditor/issues/23#issuecomment-286912973 "Try out new withExEditor which embedded WebExtensions · Issue #23 · asamuzaK/withExEditor"), [#29](https://github.com/asamuzaK/withExEditor/issues/29 "Editor Config Path not being saved · Issue #29 · asamuzaK/withExEditor")
* Doesn't work on Cyberfox etc.
  Cyberfox or other Gecko browsers are not supported.
  I'm not sure but it might work if registory (Windows) or withexeitorhost.json (Linux/Mac)are saved in each browser's specific location.

**Comment by asamuzaK** [comment]
At first I thought about making it with Electron and putting it in binary, but in that case, you will be able to distribute it only through Windows store, Apple store, etc.?
I do not have Mac so it is impossible to distribute via the Apple store.

**Comment by ssokolow** [comment]
Why would it require distribution via the App Store? There's nothing about Electron that I'm aware of which requires App Store distribution and I've seen various Electron apps where the OSX version is just an ordinary download.

Maybe you're misunderstanding "Like Android, OSX refuses to run unsigned applications unless you toggle a preference"?

**Comment by asamuzaK** [comment]
I mean Apple developer ID. Am I wrong?
[Developer ID and Gatekeeper - Apple Developer](https://developer.apple.com/developer-id/ "Developer ID and Gatekeeper - Apple Developer")

**Comment by ssokolow** [comment]
Gatekeeper is a prerequisite for getting into the App Store, but it's really just a stricter version of Microsoft's Authenticode signing and, like Authenticode, it's not mandatory unless an organizational policy has locked out the exceptions system.

Here's Apple's guide on how users can either override it for a single application or loosen it for all applications: https://support.apple.com/en-us/HT202491

**Comment by asamuzaK** [comment]
Personally think that it is a bad habit to announce to the user that accept even if "Open untrusted app?" prompts.
Distribute a signed binary, or else, have the source code open and leave it to the user to download it or not, is somewhat better I think.

**Comment by asamuzaK** [comment]
To be honest, because it is a host that only works in the background, I am awkward to think about UI and omit it, so I admit the inconvenience to the user. :P

**Comment by ssokolow** [comment]
I focus on user experience, so I try to give users the best experience that I can without being forced to pay any ransoms... err... developer account fees.

**Comment by asamuzaK** [comment]
Well I asked once but rejected.
[1321459 - WebExtensions: Add helper UI to create/save nativeMessaging app manifest](https://bugzilla.mozilla.org/show_bug.cgi?id=1321459 "1321459 - WebExtensions: Add helper UI to create/save nativeMessaging app manifest")

**Comment by asamuzaK** [comment]
By the way, what about [#5](https://github.com/asamuzaK/withExEditorHost/pull/5 "Add troubleshooting section by asamuzaK · Pull Request #5 · asamuzaK/withExEditorHost")

**Comment by ssokolow** [comment]
I've proofread it and left my feedback. Aside from that, I see nothing wrong with it.

It's better than nothing, but I still think that things could be made easier. (If I can ever find time, maybe I'll experiment with a pull request.)

**Comment by ssokolow** [comment]
> Well I asked once but rejected.

They were saying the exact same thing I was. Use solutions like NSIS.

On Linux (and possibly OSX too), I'd  distribute withExEditorHost through NPM and have it install a command like `withexeditor-setup` which prompts the user for the path to their desired editor and then writes/overwrites all of the necessary configuration files... sort of like how most DOS games would copy the installer onto the hard drive, where it would detect that the game was already installed and skip right to the sound card (re-)configuration.)

**Comment by ssokolow** [comment]
The `withexeditor-setup` option could even be made one step nicer by trying to call one or more of these commands if `process.stdout.isTTY` is false:

GTK+ desktops:
```sh
zenity --entry --title "withExEditor Setup" --text "Please enter the path to your desired text editor" --entry-text /the/old/value
```

KDE without enough GTK+ applications:
```sh
kdialog --title "withExEditor Setup"  --inputbox "Please enter the path to your desired text editor" /the/old/value
```

...and, for MacOS, [there's always AppleScript](http://blog.sapegin.me/all/show-gui-dialog-from-shell).
