### ISSUE TITLE
Support for SeaMonkey

### ISSUE THREAD

**Issue by andalou** [asamuzaK/withExEditorHost#43]
Isn't there any possibility to add support for SeaMonkey browser on Windows?

**Comment by asamuzaK** [comment]
Not planned.



On 2018年11月29日 0:26:56 JST, andalou <notifications@github.com> wrote:
>Isn't there any possibility to add support for SeaMonkey browser on
>Windows?

-- 
Kazumasa Hasegawa <kazz@asamuzak.jp>

**Comment by asamuzaK** [comment]
Additional notes:
The current SeaMonkey is equivalent to Firefox 52.
withExEditor only supports up to the current ESR version that is Firefox 60.x.

**Comment by andalou** [comment]
Does it mean that withExEditor supports the current SeaMonkey (Firefox 52)?
Thanks

**Comment by asamuzaK** [comment]
No, only Firefox 60 and later.
