### ISSUE TITLE
security - avoid #!/usr/bin/env bash

### ISSUE THREAD

**Issue by kurahaupo** [asamuzaK/withExEditorHost#46]
Please ensure that any scripts that are installed do _not_ start with `#!/usr/bin/env` after the installation process has completed.

There's a meme that the "portable" way to write a Bash script is to use `#!/usr/bin/env bash`. However this is only intended for quick-and-dirty demonstration scripts which will be downloaded and used once by naive users on "normal" POSIX systems such as MacOS.

When installing for ongoing use (and in most other cases) it's a bad idea to leave them that way; rather, adjusting the `#!` line should be part of the installation process or the packaging process (if the path to Bash can be deduced from package dependencies).

In the case of GNU/Linux systems, Bash is always available as `/bin/bash`. Embedded systems such as Android/Linux may have Bash at other paths, but then those systems _don't_ have `/usr/bin/env` either, so using it doesn't help.

MacOS also has `/bin/bash` but it's typically ancient, which is why people want to install newer versions. In this case detecting the location of Bash should be part of the installation process for any script that depends on a newer version of Bash.

For a generalized installation procedure, see [gist/kurahaupo/8130030](https://gist.github.com/kurahaupo/8130030).

**Comment by asamuzaK** [comment]
Moved to [security - avoid #!/usr/bin/env bash · Issue #25 · asamuzaK/webExtNativeMsg](https://github.com/asamuzaK/webExtNativeMsg/issues/25)

**Comment by asamuzaK** [comment]
I think that it is fixed in v4.2.0
Please verify.

**Comment by asamuzaK** [comment]
Consider this issue is already fixed so close this issue.
Feel free to reopen.
