### ISSUE TITLE
Setup hangs after creating files

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/withExEditorHost#55]
Take over [Setup hangs after creating files · Issue #109 · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/issues/109)

**Comment by shtrom** [comment]
Perfect. Thanks for the quick fix!

**Comment by asamuzaK** [comment]
Move this line
`process.on("exit", handleExit);`
https://github.com/asamuzaK/withExEditorHost/blob/master/index.js#L36

and also this line
`process.stdin.on("data", readStdin);`
https://github.com/asamuzaK/withExEditorHost/blob/master/index.js#L39

above this line.
`func = startup();`
https://github.com/asamuzaK/withExEditorHost/blob/master/index.js#L57

Refactored code should look like this:
```
if (!(setup || ver)) {
  process.on("exit", handleExit);
  process.stdin.on("data", readStdin);
  func = startup();
}
```

What happens then?

**Comment by asamuzaK** [comment]
Please check if the issue has been fixed?

**Comment by asamuzaK** [comment]
I could reproduce the issue.
Not fixed yet

**Comment by shtrom** [comment]
Yup, confirmed that the issue is still there. Odd that it wasn't yesterday... I must have still been running off my fix...
