### ISSUE TITLE
Problem with instructions for withExEditorHost

### ISSUE THREAD

**Issue by JontAlle** [asamuzaK/withExEditorHost#58]
I downloaded vers 5.0.2 and unzipped, etc
When I try to run index.js it is not executable.
The instructions say:
Next, open "cmd.exe" on Windows, "terminal" on Linux / Mac, change directory to where you saved withExEditorHost, execute the following command.
....`
> cd path/to/withExEditorHost
> index setup

However the index file is "index.js" and its not +x. So I chmod +x index.js
then ./index.js setup
fails
./index.js: line 1: /backup: Is a directory
./index.js: line 2: dest: command not found
./index.js: line 3: dest/: Is a directory
./index.js: line 4: use strict: command not found
./index.js: line 5: /backup: Is a directory
./index.js: line 6: syntax error near unexpected token `('
./index.js: line 6: `const {logErr, throwErr} = require("./modules/common");'

So somehow I figured to run
 npm run setup
npm install --production && node ./index.js setup
npm notice created a lockfile as package-lock.json. You should commit this file.
added 38 packages from 21 contributors and audited 4138 packages in 4.935s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

[1] firefox
[2] chrome
[3] chromium
[4] vivaldi
[0] CANCEL

Select a browser. [1...4 / 0]: 
...
Input editor path: /usr/bin/gvim
Input command line options: 
Created: /home/jba/.config/withexeditorhost/config/firefox/editorconfig.json

This was not the only problem. I use fedora, and there was no obvious path to upgrade to Firefox 66. But I discovered after some effort the command is:

 sudo dnf upgrade firefox
This offers me the latest version:
 firefox              x86_64              66.0-6.fc29                 updates               89 M

I suggest you clean up the install instructions. They seem far off target.

**Comment by asamuzaK** [comment]
Travis is having trouble, so v5.0.2 binaries for each operating system have not been distributed yet.
See [Travis CI Status - Slow booting Linux builds](https://www.traviscistatus.com/)

I think you're probably trying to setup the host from the source code, in that case, see [Host setup from source code](https://github.com/asamuzaK/withExEditorHost#host-setup-from-source-code) section.
