### ISSUE TITLE
not launching editor anymore

### ISSUE THREAD

**Issue by Li-An** [asamuzaK/withExEditorHost#60]
Hello, the extension did not work anymore for some times and I saw I had to upgrade the host. I got no error in option page but the editor does not launch. Did I miss something ?

**Comment by asamuzaK** [comment]
More details please.
Which host are you using? binary? npm?
If npm, is your node.js >= v10?
And which browser and OS?

**Comment by Li-An** [comment]
Sorry, Is should have given more informations.

Win 64 bits and I used binary I suppose. I updated index.exe file.

After reading your answer I decided to install node.js and followed the instructions given. Everything seems to be OK but the editor is not launched properly.

**Comment by asamuzaK** [comment]
Did you run setup script when you switch to npm?
If not, please do, and restart your browser.

How to check extension errors in Blink:
* open chrome://extensions/ from "more tools" -> "extensions"
* click Inspect views "html/background.html" of withExEditor
* select "console" tab
Any errors there?

**Comment by Li-An** [comment]
I did run the setup script (I changed the editor to Notepad++).

No error in Console tab :-(

I will try to test with Firefox.

**Comment by Li-An** [comment]
OK, it works with Firefox. 
I tested on Cent Browser deactivating all the other extensions and same problem.

I will make a test with Chrome.

**Comment by asamuzaK** [comment]
Did you choose "3"(chrome) or "6"(centbrowser) when setting up the host?

**Comment by Li-An** [comment]
I choose CentBrowser :-)

**Comment by Li-An** [comment]
It works with Chrome so it seems the problem is relative to CentBrowser. I will contact the developer.

**Comment by asamuzaK** [comment]
Confirmed. It's not working on CentBrowser.

I'm not sure but maybe it is because of the Chromium version?

CentBrowser 3.9.2.45 Chromium: 72.0.3626.121 -> not working
Brave 0.62.51 Chromium: 73.0.3683.103 -> works
Vivaldi (Snapshot) 2.5.1511.4 Chrome/74.0.3729.55 -> works

There was a similar issue the past.
Ref [Errors with chrome 69 · Issue #94 · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/issues/94)

**Comment by Li-An** [comment]
Thanks for taking time for this. I wait for an eventual answer from Cent Browse’s developer.

**Comment by Li-An** [comment]
Cent Browser’s developer will try to fix it.

**Comment by asamuzaK** [comment]
Can you tell me where I can track it?

**Comment by asamuzaK** [comment]
Oh, found it.
[problem with WithExEditor extension](https://www.centbrowser.com/forum/showthread.php?tid=2735)
