### ISSUE TITLE
[Browser] Brave on Linux

### ISSUE THREAD

**Issue by smiglo** [asamuzaK/withExEditorHost#61]
Hi,

Do you have a plan to add support for Brave browser on Linux? I see it is for Windows already.

Thanks.

**Comment by asamuzaK** [comment]
Would you contact Brave developer and tell me where to save the [application manifest](https://developer.chrome.com/apps/nativeMessaging#native-messaging-host-location) in Brave on Linux?

**Comment by asamuzaK** [comment]
OK, I found it.
`~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/`

**Comment by asamuzaK** [comment]
Released v5.1.1 which supports Brave on Linux
