### ISSUE TITLE
editorPath symlink wrongly resolved by index setup

### ISSUE THREAD

**Issue by Smylers** [asamuzaK/withExEditorHost#62]
Invoking an editor initially failed for me, because `./index setup` changed the value I gave it for my editor.

I ran `./index setup` and for ‘Input editor path’ I specified `/usr/bin/gvim`. That wrote *editorconfig.json* with `editorPath` set to `/usr/bin/vim.gtk3` — which doesn't work.

This is on Ubuntu Linux, and `/usr/bin/gvim` is indeed a chain of 2 symlinks which resolve to `/usr/bin/vim.gtk3`, so both paths refer to the same file.

But Vim behaves differently depending on how it is invoked. Specifically, it needs the command to be `gvim` to open in an X window; otherwise it expects to be in a terminal, and can't start when it isn't, complaining:

> withexeditorhost: childProcess_stderr
> Vim: Warning: Output is not to a terminal
> Vim: Warning: Input is not from a terminal

![image](https://user-images.githubusercontent.com/598534/60677021-4a38a080-9e78-11e9-96c2-7ff3e927e1d3.png)

The workaround is to manual edit *editorconfig.json* after running `./index setup`, replacing the wrong command name with the correct one.

But it would be much better if the set-up program simply wrote what I typed in there in the first place, rather than replacing it with something else. Thanks.

**Comment by asamuzaK** [comment]
Fixed
Try v5.1.3

**Comment by Smylers** [comment]
Perfect, thank you!

That was amazingly quick bug-fixing.
