### ISSUE TITLE
Script for installing withExEditorHost

### ISSUE THREAD

**Issue by mb720** [asamuzaK/withExEditorHost#73]
I remember that when first using withExEditor, installing the corresponding host wasn't too easy.

Since then I've automated installation using the following script. It downloads the host from GitHub using cURL, extracts it with 7z and points `withexeditorhost.sh` to the host's index file:

    #! /usr/bin/env bash

    # Install the host for withExEditor that allows editing text in Firefox using a text editor like Vim.
    # After executing this script, reload the Firefox plugin
    withExEditorHostRemoteFile="https://github.com/asamuzaK/withExEditorHost/releases/download/v5.3.0-b.2/linux-x86_64.zip"
    withExEditorHostLocalZipFile="/tmp/withExEditorHost.zip"
    withExEditorHostDir="$HOME/.local/bin/withExEditorHost"

    # Create the dir for the host's index file, download the archive and unzip it
    mkdir --parents "$withExEditorHostDir"; curl -L -o "$withExEditorHostLocalZipFile" "$withExEditorHostRemoteFile" && 7z x "$withExEditorHostLocalZipFile" -o"$withExEditorHostDir"

    indexFile="$withExEditorHostDir/index"
    hostScript="$HOME/.config/withexeditorhost/config/firefox/withexeditorhost.sh"

    # The Firefox plugin will use this shell script to call the host's index file
    printf "#! /usr/bin/env bash\n'$indexFile'\n" > "$hostScript"

    chmod +x "$indexFile" "$hostScript"

I'm posting it here for three reasons:

  * For other users to benefit
  * You, asamuzaK, might want to include it as part of your installation instructions
  * Perhaps somebody knows how to not hardcode the version number in `withExEditorHostRemoteFile`, maybe replacing it with a URL of the latest release

**Comment by asamuzaK** [comment]
How about adding a section for that on [withExEditorHost/README.md](https://github.com/asamuzaK/withExEditorHost/blob/master/README.md) like below?

```
## Host setup

NOTE: If you already have Node.js installed, it is recommended to get the host from npm.
Refer to [Host setup from npm](#host-setup-from-npm) below.

(snip)

### Update

Before upgrading a host, disable withExEditor installed in your browser.
To upgrade, just overwrite binary files, that's all.
There is no need to run the setup script again after the upgrade.
Enable withExEditor after the upgrade.

### Automated installation

#### Linux

(Add description and sample script here)

***

## Host setup from npm

(snip)
```

> Perhaps somebody knows how to not hardcode the version number in withExEditorHostRemoteFile, maybe replacing it with a URL of the latest release

You can get metadata from [registry.npmjs.org/withexeditorhost](https://registry.npmjs.org/withexeditorhost).
Fetch that file and parse as JSON.
Latest version is in `dist-tags > latest` field.

```
{
  dist-tags: {
    latest: "5.2.1",
  }
}
```

When your ready, please file a PR.
Thanks.

**Comment by mb720** [comment]
Thanks for the tip for getting the version. [Here's](https://github.com/asamuzaK/withExEditorHost/pull/74) the PR.
