### ISSUE TITLE
Support for Chrome Beta

### ISSUE THREAD

**Issue by rtoy** [asamuzaK/withExEditorHost#75]
I can't remember for sure, but it seems to me that a while ago, the setup menu included an entry from Chrome beta.  That seems to be gone now.  I typically run Chrome beta as my primary Chrome browser instead of stable.

Likewise, there used to be support for Firefox Nightly.  That doesn't seem to be there anymore.  I use Firefox nightly quite often as my main FF browser.  I also use Firefox stable release.

Do I have to set these up manually now?

**Comment by asamuzaK** [comment]
Tell me the profile path of Chrome Beta.

1. Navigate to chrome://version
2. Look for the `Profile Path` field. This gives the path to the profile.

**Comment by rtoy** [comment]
It's $HOME/.config/google-chrome-beta/Default

**Comment by asamuzaK** [comment]
Released v5.3.1

**Comment by asamuzaK** [comment]
As for Firefox Nightly, I don't see any document in Mozilla docs.
At least on Windows, Release and Nightly share the native messaging host configuration.
If Nightly needs its own setting on Linux or MacOS, create a new issue.

**Comment by rtoy** [comment]
I'll have to check Firefox Nightly later, but Chrome Beta works fine now.  Thanks!
