### ISSUE TITLE
Using external editor causes Simplenote to hang

### ISSUE THREAD

**Issue by ddirks** [asamuzaK/withExEditorHost#77]
For some time, I have used the withExEditorHost to launch gVim from Firefox (Windows 10 Pro). Recently, I have noticed that when editing a note in the Simplenote web interface, when gVim closes the Simplenote text is updated, but with extra linefeeds (or maybe it's \cr\lf instead of just \cr -- I'm not sure), and the Simplenote site itself becomes unresponsive. The edited note is no longer saved as expected.

I have no idea if this change in behavior occurred due to a change in the withExEditorHost, a change in the Simplenote web interface, or something unrelated to either of them, like a change in Windows. I see the same behavior on several Windows machines, some at my office and some at home, so it doesn't appear to be a specific security setting for firewall issue.

I'm starting here because the withExEditorHost seems to change more often than Simplenote (as far as I can tell.)

Thanks for any ideas or suggestions regarding how I can try to debug the situation.

I've attached a text file with the errors that show up in the browser console after exiting gVim.

[simplenote_withExEditor_error.txt](https://github.com/asamuzaK/withExEditorHost/files/4207202/simplenote_withExEditor_error.txt)

**Comment by asamuzaK** [comment]
[Simplenote](https://github.com/Automattic/simplenote-electron) is a [React](https://reactjs.org/) app, and React uses [Draft.js](https://draftjs.org/) for text editor.
But withExEditor currently does not support Draft.js.

Follow asamuzaK/withExEditor#123

**Comment by ddirks** [comment]
Thanks for the explanation. I'll keep an eye on the issue you mentioned.

**Comment by asamuzaK** [comment]
@ddirks 
asamuzaK/withExEditor#123 is fixed on Blink (Chrome and its variants).
Can you check if it works or not on Simplenote with Chrome?

**Comment by ddirks** [comment]
I just installed withExEditor in Chrome (ver 84.0.4147.105, 64-bit Windows 10), and it does in fact work with Simplenote! Thanks for that!

As you're no doubt aware, the behavior in Firefox has evolved since the original report back in February. Now, when I edit a Simplenote page with the external editor, closing the editor simply doesn't change the original Simplenote text. I see https://github.com/asamuzaK/withExEditor/issues/138 seems to be addressing exactly that.

For reference, I have withExEditorHost v. 5.4.3 installed.

**Comment by asamuzaK** [comment]
Thanks.

This issue is not a host issue so I'll close here.
Please follow asamuzaK/withExEditor#138
