### ISSUE TITLE
Please document installation prerequisites

### ISSUE THREAD

**Issue by kurahaupo** [asamuzaK/withExEditorHost#78]
I tried to short-cut the installation process by directly downloading the linux-x86 zip file.
I unpacked it and checked the `index` (ELF binary), using `ldd`:

$ <code> mv ~/Downloads/linux-x86.zip ~/Downloads/withExEditorHost-linux-x86.zip </code>
$ <code> mkdir ~/tmp/with-ex-editor-host </code>
$ <code> cd ~/tmp/with-ex-editor-host </code>
$ <code> unzip ~/Downloads/withExEditorHost-linux-x86.zip </code>
```
Archive:  ~/Downloads/withExEditorHost-linux-x86.zip
  inflating: LICENSE                 
  inflating: README.md               
  inflating: README.ja.md            
  inflating: index                   
```
$ <code> chmod a+x index </code>
$ <code> ldd index </code>
```
./index: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./index)
./index: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./index)
./index: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./index)
        linux-gate.so.1 =>  (0xf...c000)
        libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf...b000)
        libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf...3000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf...d000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf...0000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf...4000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf...2000)
        /lib/ld-linux.so.2 (0xf...e000)
```
$ <code> $ uname -m </code>
```
x86_64
```
These symbol errors do of course prevent the file from being run.

It would be helpful to know ahead of time which other software needs to be downloaded before attempting to install the pre-built package, or to build and install from source.

**Comment by asamuzaK** [comment]
your os is 64bit, download binary for that

**Comment by kurahaupo** [comment]
That's obvious in hindsight, which is why I've raised this as a
documentation issue.

I didn't use the download procedure, I used linux-x86.zip that was within
the code repo, where there is no x86_64 version.

I only read the download instructions subsequently.

**Comment by asamuzaK** [comment]
then update the document and file a pull request
thanks
