### ISSUE TITLE
message about v.5.4.2 still showing

### ISSUE THREAD

**Issue by Li-An** [asamuzaK/withExEditorHost#85]
Hello, I copied all files from v.4.5.2 in withExEditorHost directory but it stills shows a warning in browser.

**Comment by asamuzaK** [comment]
More info please.
OS, browser, and I suppose you are talking about binary?

**Comment by Li-An** [comment]
Sorry.
Cent Browser (Chrome), Win 10 64 bits. I’m not sure I understand *binary* but I downloaded the zip package here.

**Comment by asamuzaK** [comment]
I found an issue you posted before.
https://github.com/asamuzaK/withExEditorHost/issues/60

In that thread, you said that you switched to npm.
Did you switch back again?

If you are still using npm, exec cmd.exe and run `npm up -g`

**Comment by Li-An** [comment]
I cannot remember. How can I check this ?

**Comment by asamuzaK** [comment]
* Open explorer
* Navigate to `C:\Users\[YOUR_USER_NAME]\AppData\Roaming\withexeditorhost\config\chrome`
* Open `withexeditor.cmd` with a text editor

Content of `withexeditor.cmd` should be
```
@echo off
[cmd] [file]
```

If [cmd] is `"C:\Program Files\nodejs\node.exe"` or something like that, and [file] is `C:\Users\[YOUR_USER_NAME]\AppData\Roaming\npm\node_modules\withexeditorhost\index.js`, then you are using npm.

If [cmd] is a path to the binary you saved, for example `C:\Users\[YOUR_USER_NAME]\withExeditor\index.exe`, and [file] is `C:\Users\[YOUR_USER_NAME]\withExeditor\index.js`, then you are using binary.

**Comment by Li-An** [comment]
Thanks : I use binary.

**Comment by asamuzaK** [comment]
I've installed Cent browser, but could not confirm the issue.

* Exec cmd.exe and locate to the path of the binary `cd C:\Users\[YOUR_USER_NAME]\path\to\withExEditorHost`
* Run `index -v`

Does it echo `5.4.2`?

**Comment by Li-An** [comment]
If I type `cd C:\Users\Seven\path\to\withExEditorHost` I have a **not found** message. I made a search on my profile and found one directory that can be the good one `C:\Users\Seven\AppData\Local\withExEditorHost`

If I type index -v, a prompt asks me to open a file and then see capture

[![7121942ccdba19f6b5547cc0e1341142.md.png](https://tof.cx/images/2020/04/11/7121942ccdba19f6b5547cc0e1341142.md.png)](https://tof.cx/image/q3nhaG)

**Comment by asamuzaK** [comment]
Looks like a log of VS Code? I'm not sure though.

Anyway, I think you should install host again.

**Comment by Li-An** [comment]
You are right, the prompt makes me open the file in VS Code. 
OK, I will try to install it again.

**Comment by Li-An** [comment]
I reinstalled it and it’s OK.
