### ISSUE TITLE
Extract native-message.js to its own repository

### ISSUE THREAD

**Issue by DamienCassou** [asamuzaK/withExEditorHost#9]
Hi,

in the context of a web extension I'm working on, I included your repository as a submodule because of your really good native-message.js. Would it make sense to extract that to its own project so people can just include it using package.json without getting withExEditorHost? I can take care of the extraction if you want to.

**Comment by asamuzaK** [comment]
I don't have time now, but will work on it soon.

**Comment by DamienCassou** [comment]
On July 12, 2017 1:05:44 PM GMT+02:00, "asamuzaK (Kazz)" <notifications@github.com> wrote:
>I don't have time now, but will work on it soon.

I have some time now if you need.
-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by asamuzaK** [comment]
Thanks, but I think I can start working on this in a week or so.
By the way, is it okay to only support node v8?
v8 will become LTS this fall.
Or should it support v6 too?

**Comment by DamienCassou** [comment]
On July 12, 2017 1:45:44 PM GMT+02:00, "asamuzaK (Kazz)" <notifications@github.com> wrote:
>Thanks, but I think I can start working on this in a week or so.
>By the way, is it okay to only support node v8?
>v8 will become LTS this fall.
>Or should it support v6 too?

I'm OK with whatever suits you best.
-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by asamuzaK** [comment]
Added repo, no docs yet.
[asamuzaK/webExtNativeMsg: Native messaging host modules for WebExtensions](https://github.com/asamuzaK/webExtNativeMsg "asamuzaK/webExtNativeMsg: Native messaging host modules for WebExtensions")

**Comment by asamuzaK** [comment]
Can I close this?

**Comment by DamienCassou** [comment]
Thank you very much!
