### ISSUE TITLE
Update `Automated installation` doc

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/withExEditorHost#92]
@mb720 

Starting from v6.0.0, release assets for linux (and macos) will be `*.tar.gz`.
Please update the automated installation doc and the source code.

Thanks.

**Comment by mb720** [comment]
Sure. Can you make v6.0.0-a.30 the current pre-release version? The reason is that I'd like to test the install script and currently the following command returns `5.5.0-b.1`, a version which still uses a .zip archive for the Linux files:

    curl --silent https://registry.npmjs.org/withexeditorhost | jq --raw-output ".\"dist-tags\".\"next\""

**Comment by asamuzaK** [comment]
Done.
https://registry.npmjs.org/withexeditorhost

Thank you for your contribution.

**Comment by asamuzaK** [comment]
Fixed by #93
