### ISSUE TITLE
Chrome beta location for Mac OSX has changed

### ISSUE THREAD

**Issue by rtoy** [asamuzaK/withExEditorHost#98]
Currently setting up the host on Mac OS only provides choices for chrome and chrome canary because chrome beta was using the same path as chrome.  However, I noticed now that when running Chrome beta, withExEditor isn't available.  This used to work.

I think it's because the path has changed. I think it's now `~/Library/Application Support/Google/Chrome Beta/`.  This goes along with plain Google/Chrome and Google/Chrome Canary.

**Comment by asamuzaK** [comment]
The issue has been fixed, but I'm currently having trouble deploying binaries
Please note that the new release will be after this deployment issue is resolved.
