### ISSUE TITLE
editor args for Notepad++ /  "Editor State Unknown" 

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [asamuzaK/withExEditorHost#99]
Win 10, Firefox 85, current notepad++

I had the old version 2.7 installed, downloaded the current zip and unzipped it into a new folder. Then I ran "index setup" - Firefox - yes - yes - editor path - editor args: <????>

At first I entered nothing, in second trial I entered "''" - both ended with ..
- an installed plugin
- missing commands in Text fields
- the information:  "Editor State Unknown "

Which args to I need for Notepad++? Is it defined somewhere?

Regards!

**Comment by asamuzaK** [comment]
Can I close this as dupe of #100 ?

**Comment by Pierre-de-la-Verre** [comment]
These are two (connected) points - #100 is only for the file-path, this here is for the next input. It seems that the main problem is caused by #100 , but a common info (help) for this input would also be helpful for the users.

**Comment by asamuzaK** [comment]
If you don't need the command arguments, just press Enter key.

Added a confirmation to ask if to execute editor with command arguments, and if yes then prompt.

**Comment by Pierre-de-la-Verre** [comment]
Thanks, works fine for me.
